# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

#exclude volumes and node_modules/dist in child directories
exclude: '^(volumes|.*[\/\\](node_modules|dist)([\/\\]?.*)?)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: server-ts
        name: server ts typecheck
        language: system
        entry: bash -c "npm --prefix server run typecheck"
        types: [file]
      - id: server-linter
        name: server linter
        language: system
        entry: bash -c "npm --prefix server run lint"
