services:
  app:
    build:
      target: dev
      context: ./server
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - local
    develop:
      watch:
        - action: sync
          target: /app
          path: ./server
          ignore:
            - node_modules
            - dist
            - volumes
        - action: rebuild
          path: package.json

  db:
    image: postgres:17.2-alpine3.21
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=borys
      - POSTGRES_DB=courses_side
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  db:
